### ISSUE TITLE
Syntax coloring is incorrect for inline comments

### ISSUE THREAD

**Issue by eric-burel** [IronGeek/vscode-env#12]
Example:
```
FOOBAR= # set foobar here
```
Result:
![image](https://user-images.githubusercontent.com/7983005/202844275-2ef56689-2a9d-42c7-9413-589146b6a7e5.png)

The comment should be displayed as text.

I think more broadly anything after "=" should be displayed in the same color, avoiding risks of confusions

**Comment by IronGeek** [comment]
Thank you for filling this issue.

I've tested your example using [motdotla/dotenv](https://github.com/motdotla/dotenv) and [joho/godotenv](https://github.com/joho/godotenv)

In both test, the comment is actually treated as comment (ignored)
The `FOOBAR` value in this case is `<empty string>`

To treat any string with hash (`#`) as part of the value itself instead of comment, you actually need to wrap it in quotes:
```env
# this is a comment
FOOBAR=value
FOOBAR_COMMENT=value # comment
FOOBAR_QUOTED="value"
FOOBAR_QUOTED_COMMENT="value" # comment
FOOBAR_EMPTY=
FOOBAR_EMPTY_COMMENT= # comment
FOOBAR_EMPTY_QUOTED_COMMENT="" # comment
FOOBAR_QUOTED_HASH="value # comment"
FOOBAR_SQUOTED_HASH='value # comment'
```

just in case GitHub syntax highlighting is not working:
![image](https://user-images.githubusercontent.com/1383932/202850438-220287a5-8494-4b6c-8127-1f258a65051e.png)

What env parser implementation are you using?
Is the `# set foobar here` in `FOOBAR= # set foobar here` actualy treated as value?

**Comment by eric-burel** [comment]
Hi, thanks for your fast reply and experiment, this helped a lot understanding the issue.

This is an issue that affects Next.js apps during build, I've built a repro.

Closing this issue as indeed inline comments are expected to work as intended with dotenv, so your plugin works as expected.
